version: '3.9'

services:

  test:
    build:
      context: .
      dockerfile: Dockerfile.test

  messaging_api:
    container_name: messaging_api-main
    image: messaging-api-img:1.0
    restart: always
    ports:
      - "9000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - test
